#import "ConciseKit.h"
#import "NSApplication+SharedObjects.h"
#import "NSDictionary+PFMAdditions.h"
#import "NSMutableDictionary+PFMAdditions.h"
#import "NSDate+SCAdditions.h"
#import "NSWindow+PFMAdditions.h"

#define kPathAPIHost                  @"https://api.path.com"
#define kPathDefaultsEmailKey         @"user_email"
#define kPathKeychainServiceName      @"Path For Mac"
